apiVersion: v1
kind: LimitRange
metadata:
  name: my-limit-range
spec:
  limits:
    - type: Container
      defaultRequest:
        cpu: 100m
        memory: 128Mi
      default:
        cpu: 200m
        memory: 256Mi
      min:
        cpu: 100m
        memory: 128Mi
      max:
        cpu: 200m
        memory: 256Mi
---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: my-cron-job
  namespace: three
spec:
  schedule: '*/1 * * * *'
  jobTemplate:
    metadata:
      name: my-cron-job
    spec:
      template:
        metadata:
          labels:
            question: three
        spec:
          restartPolicy: OnFailure
          containers:
            - image: busybox
              name: my-cron-job
              command:
                - /bin/sh
                - -c
                - date